pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.namespace == 'com.damianhoward') {
                useModule("com.github.damianhoward.build-conventions:plugins:${requested.version}")
            }
        }
    }
}

rootProject.name = 'bank-csv-to-qif'
